In [1]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
import pandas as pd
import numpy as np

In [2]:
from ucimlrepo import fetch_ucirepo
spambase = fetch_ucirepo(id=94)
X = spambase.data.features
y = spambase.data.targets

In [3]:
#X is already vectorized
X

word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0               0.00               0.64           0.64           0.0   
1               0.21               0.28           0.50           0.0   
2               0.06               0.00           0.71           0.0   
3               0.00               0.00           0.00           0.0   
4               0.00               0.00           0.00           0.0   
...              ...                ...            ...           ...   
4596            0.31               0.00           0.62           0.0   
4597            0.00               0.00           0.00           0.0   
4598            0.30               0.00           0.30           0.0   
4599            0.96               0.00           0.00           0.0   
4600            0.00               0.00           0.65           0.0   

      word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0              0.32            0.00              0.00                0.00   
1              0.14            0.28              0.21                0.07   
2              1.23            0.19              0.19                0.12   
3              0.63            0.00              0.31                0.63   
4              0.63            0.00              0.31                0.63   
...             ...             ...               ...                 ...   
4596           0.00            0.31              0.00                0.00   
4597           0.00            0.00              0.00                0.00   
4598           0.00            0.00              0.00                0.00   
4599           0.32            0.00              0.00                0.00   
4600           0.00            0.00              0.00                0.00   

      word_freq_order  word_freq_mail  ...  word_freq_conference  char_freq_;  \
0                0.00            0.00  ...                   0.0        0.000   
1                0.00            0.94  ...                   0.0        0.000   
2                0.64            0.25  ...                   0.0        0.010   
3                0.31            0.63  ...                   0.0        0.000   
4                0.31            0.63  ...                   0.0        0.000   
...               ...             ...  ...                   ...          ...   
4596             0.00            0.00  ...                   0.0        0.000   
4597             0.00            0.00  ...                   0.0        0.000   
4598             0.00            0.00  ...                   0.0        0.102   
4599             0.00            0.00  ...                   0.0        0.000   
4600             0.00            0.00  ...                   0.0        0.000   

      char_freq_(  char_freq_[  char_freq_!  char_freq_$  char_freq_#  \
0           0.000          0.0        0.778        0.000        0.000   
1           0.132          0.0        0.372        0.180        0.048   
2           0.143          0.0        0.276        0.184        0.010   
3           0.137          0.0        0.137        0.000        0.000   
4           0.135          0.0        0.135        0.000        0.000   
...           ...          ...          ...          ...          ...   
4596        0.232          0.0        0.000        0.000        0.000   
4597        0.000          0.0        0.353        0.000        0.000   
4598        0.718          0.0        0.000        0.000        0.000   
4599        0.057          0.0        0.000        0.000        0.000   
4600        0.000          0.0        0.125        0.000        0.000   

      capital_run_length_average  capital_run_length_longest  \
0                          3.756                          61   
1                          5.114                         101   
2                          9.821                         485   
3                          3.537                          40   
4                          3.537              

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=10)

In [6]:
lrmodel = LogisticRegression()

svmmodel = SVC()

nbmodel = MultinomialNB()

In [7]:
def evaluvate(model):
    model.fit(X_train,y_train)
    y_predicted=model.predict(X_test)
    print(model.score(X_test,y_test))
    cm = confusion_matrix(y_test, y_predicted)
    print(cm)
    print(classification_report(y_test, y_predicted))    

In [8]:
evaluvate(lrmodel)

0.9283387622149837
[[527  32]
 [ 34 328]]
              precision    recall  f1-score   support

           0       0.94      0.94      0.94       559
           1       0.91      0.91      0.91       362

    accuracy                           0.93       921
   macro avg       0.93      0.92      0.92       921
weighted avg       0.93      0.93      0.93       921



C:\Users\premk\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\premk\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [9]:
evaluvate(svmmodel)

C:\Users\premk\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.7339847991313789
[[504  55]
 [190 172]]
              precision    recall  f1-score   support

           0       0.73      0.90      0.80       559
           1       0.76      0.48      0.58       362

    accuracy                           0.73       921
   macro avg       0.74      0.69      0.69       921
weighted avg       0.74      0.73      0.72       921



In [10]:
evaluvate(nbmodel)

0.8121606948968513
[[471  88]
 [ 85 277]]
              precision    recall  f1-score   support

           0       0.85      0.84      0.84       559
           1       0.76      0.77      0.76       362

    accuracy                           0.81       921
   macro avg       0.80      0.80      0.80       921
weighted avg       0.81      0.81      0.81       921



C:\Users\premk\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [11]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from tensorflow.keras import Sequential, layers
import tensorflow as tf

In [12]:
input_shape = X_train.shape[1]
model = Sequential([
  layers.Dense(128, activation='relu', input_shape=(input_shape,)),
  layers.Dense(64, activation='relu'),
  layers.Dense(2, activation='softmax')
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(), #not one hot code 
              metrics=['accuracy'])

C:\Users\premk\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [16]:
model.fit(X_train, y_train, epochs=10, batch_size=10)

Epoch 1/10
368/368 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - accuracy: 0.8813 - loss: 0.4791
Epoch 2/10
368/368 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8723 - loss: 0.9095
Epoch 3/10
368/368 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9007 - loss: 0.5530
Epoch 4/10
368/368 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8946 - loss: 0.3971
Epoch 5/10
368/368 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9224 - loss: 0.2430
Epoch 6/10
368/368 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8541 - loss: 1.3203
Epoch 7/10
368/368 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9163 - loss: 0.2921
Epoch 8/10
368/368 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8878 - loss: 0.5477
Epoch 9/10
368/368 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9246 - loss: 0.2295
Epoch 10/10
368/368 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9125 - loss: 0.2478


In [46]:
y_pred=model.predict(X_test)
y_pred=np.argmax(y_pred,axis=1)

29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step


In [47]:
y_pred[:10]

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 0], dtype=int64)

In [48]:
y_test=y_test.to_numpy() #converting to numpy array

In [49]:
def accuracy(y_pred,y):
    noofcorrect=0
    for i,j in zip(y_pred,y):
        if i==j:
            noofcorrect+=1
    return noofcorrect/len(y)
    

In [50]:
accuracy(y_pred,y_test)

0.8957654723127035

In [51]:
#Conclusion - LR and neural network performs best